### ISSUE TITLE
Stylus CSS issue

### ISSUE THREAD

**Issue by shazr** [playcode/playcode#10]
Switching to Stylus as the CSS preprocessor seems to throw a JS exception in the browser 
I'm working on both Vivaldi and Yandex (basically Chrome)

"undefined:1 Uncaught (in promise) TypeError: Illegal invocation"

ReferenceError: initWorker is not defined
    at https://playcode.io/static/js/main.6debf8d.js:2:11155
    at https://playcode.io/static/js/main.6debf8d.js:2:11219
    at Object.c.compile (https://playcode.io/static/js/main.6debf8d.js:2:10903)
    at https://playcode.io/static/js/main.6debf8d.js:2:22440
    at Array.forEach (native)
    at https://playcode.io/static/js/main.6debf8d.js:2:22382
    at compileChanged (https://playcode.io/static/js/main.6debf8d.js:2:22324)
    at Array.<anonymous> (https://playcode.io/static/js/vendor.007a2bc.js:6:3463)
    at M.dispatch (https://playcode.io/static/js/vendor.007a2bc.js:6:8659)
    at M.dispatch (https://playcode.io/static/js/vendor.007a2bc.js:6:7715)

**Comment by happierall** [comment]
Thank you. Fixed.
